default:
	g++ -o rubik rubik.cpp -lGL -lglfw -lGLEW

compile:
	g++ -o rubik rubik.cpp -std=c++11 -L/usr/local/lib -lGLEW -lGLU -lglfw3 -lrt -lXrandr -lXinerama -lXi -lXcursor -lGL -lm -ldl -lXrender -ldrm -lXdamage -lX11-xcb -lxcb-glx -lxcb-dri2 -lxcb-dri3 -lxcb-present -lxcb-sync -lxshmfence -lXxf86vm -lXfixes -lXext -lX11 -lpthread -lxcb -lXau -lXdmcp

run:
	./rubik